In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in d:\data science\new folder\lib\site-packages (1.6.12)
Requirement already satisfied: six>=1.10 in d:\data science\new folder\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: bleach in d:\data science\new folder\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: python-dateutil in d:\data science\new folder\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: certifi>=2023.7.22 in d:\data science\new folder\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: tqdm in d:\data science\new folder\lib\site-packages (from kaggle) (4.64.0)
Requirement already satisfied: python-slugify in d:\data science\new folder\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in d:\data science\new folder\lib\site-packages (from kaggle) (2.27.1)
Requirement already satisfied: urllib3 in d:\data science\new folder\lib\site-packages (from kaggle) (1.26.9)
Requirement already satisfied: webencodings in d:\data science\new folder\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: packaging in d:\data science\new folder\lib\site-packages (from bleach->kaggle) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in d:\data science\new folder\lib\site-packages (from packaging->bleach->kaggle) (3.0.4)
Requirement already satisfied: text-unidecode>=1.3 in d:\data science\new folder\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\data science\new folder\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\data science\new folder\lib\site-packages (from requests->kaggle) (3.3)
Requirement already satisfied: colorama in d:\data science\new folder\lib\site-packages (from tqdm->kaggle) (0.4.4)

In [2]:
import kaggle

In [3]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [4]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('orders.csv',na_values = ['Not Available','unknown'])

In [7]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [8]:
df.columns.str.lower()

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [9]:
df.columns = df.columns.str.replace(' ','_')

In [10]:
df.columns

Index(['Order_Id', 'Order_Date', 'Ship_Mode', 'Segment', 'Country', 'City',
       'State', 'Postal_Code', 'Region', 'Category', 'Sub_Category',
       'Product_Id', 'cost_price', 'List_Price', 'Quantity',
       'Discount_Percent'],
      dtype='object')

In [11]:
df['discount'] = df['List_Price']*df['Discount_Percent']*.01

In [12]:
df['discount']

0        5.2
1       21.9
2        0.5
3       19.2
4        1.0
        ...
9989     1.2
9990     3.6
9991     5.2
9992     0.9
9993     7.2
Name: discount, Length: 9994, dtype: float64

In [13]:
df['sale_price'] = df['List_Price']-df['discount']

In [50]:
df

,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,discount,sale_price,order_date
0,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,5.2,254.8,2023-03-01
1,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,21.9,708.1,2023-08-15
2,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,0.5,9.5,2023-01-10
3,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,19.2,940.8,2022-06-18
4,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,1.0,19.0,2022-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,1.2,28.8,2023-02-18
9990,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,3.6,86.4,2023-03-17
9991,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,5.2,254.8,2022-08-07
9992,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,0.9,29.1,2022-11-19
9993,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,7.2,232.8,2022-07-17

In [51]:
df['order_date']=pd.to_datetime(df['Order_Date'],format="%Y-%m-%d")

In [52]:
df

,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,discount,sale_price,order_date
0,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,5.2,254.8,2023-03-01
1,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,21.9,708.1,2023-08-15
2,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,0.5,9.5,2023-01-10
3,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,19.2,940.8,2022-06-18
4,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,1.0,19.0,2022-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,1.2,28.8,2023-02-18
9990,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,3.6,86.4,2023-03-17
9991,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,5.2,254.8,2022-08-07
9992,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,0.9,29.1,2022-11-19
9993,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,7.2,232.8,2022-07-17

In [47]:
df.columns

Index(['Order_Id', 'Order_Date', 'Ship_Mode', 'Segment', 'Country', 'City',
       'State', 'Postal_Code', 'Region', 'Category', 'Sub_Category',
       'Product_Id', 'cost_price', 'List_Price', 'Quantity', 'discount',
       'sale_price', 'order_date'],
      dtype='object')

In [54]:
df

,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,discount,sale_price,order_date
0,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,5.2,254.8,2023-03-01
1,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,21.9,708.1,2023-08-15
2,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,0.5,9.5,2023-01-10
3,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,19.2,940.8,2022-06-18
4,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,1.0,19.0,2022-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,1.2,28.8,2023-02-18
9990,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,3.6,86.4,2023-03-17
9991,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,5.2,254.8,2022-08-07
9992,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,0.9,29.1,2022-11-19
9993,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,7.2,232.8,2022-07-17

In [56]:
df

,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,discount,sale_price,order_date
0,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,5.2,254.8,2023-03-01
1,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,21.9,708.1,2023-08-15
2,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,0.5,9.5,2023-01-10
3,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,19.2,940.8,2022-06-18
4,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,1.0,19.0,2022-07-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,1.2,28.8,2023-02-18
9990,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,3.6,86.4,2023-03-17
9991,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,5.2,254.8,2022-08-07
9992,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,0.9,29.1,2022-11-19
9993,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,7.2,232.8,2022-07-17

In [59]:
df=df.drop('Order_Date',axis='columns')

In [19]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in d:\data science\new folder\lib\site-packages (8.3.0)Note: you may need to restart the kernel to use updated packages.

In [20]:
import mysql.connector

In [21]:
import warnings
warnings.filterwarnings('ignore')

In [22]:
pip install pymysql

Requirement already satisfied: pymysql in d:\data science\new folder\lib\site-packages (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [23]:
import sqlite3

In [24]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in d:\data science\new folder\lib\site-packages (0.5.0)
Requirement already satisfied: six in d:\data science\new folder\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: sqlparse in d:\data science\new folder\lib\site-packages (from ipython-sql) (0.5.0)
Requirement already satisfied: ipython-genutils in d:\data science\new folder\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prettytable in d:\data science\new folder\lib\site-packages (from ipython-sql) (3.10.0)
Requirement already satisfied: sqlalchemy>=2.0 in d:\data science\new folder\lib\site-packages (from ipython-sql) (2.0.29)
Requirement already satisfied: ipython in d:\data science\new folder\lib\site-packages (from ipython-sql) (8.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\data science\new folder\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\data science\new folder\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)
Requirement already satisfied: pickleshare in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: decorator in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: backcall in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: stack-data in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: colorama in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.4.4)
Requirement already satisfied: setuptools>=18.5 in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (61.2.0)
Requirement already satisfied: matplotlib-inline in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (0.1.2)
Requirement already satisfied: pygments>=2.4.0 in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: traitlets>=5 in d:\data science\new folder\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in d:\data science\new folder\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: wcwidth in d:\data science\new folder\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: executing in d:\data science\new folder\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in d:\data science\new folder\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in d:\data science\new folder\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [25]:
cnn = sqlite3.connect('retail_sales')

In [26]:
from pymysql import connect

In [38]:
db = connect(
     host="localhost",
     user="root",
     password="watan",
)
cur = db.cursor()
query = "SHOW DATABASES"
cur.execute(query)
data_bases = cur.fetchall()
for data in data_bases:
    print(data)

('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [41]:
import sqlalchemy

In [62]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:watan@localhost/sys')

...

df.to_sql('df_orders', con = engine)

9994